-- 0002: better-auth tables for the WEB DASHBOARD's human session plane.
--
-- better-auth owns human sessions + password hashing for the dashboard. These tables live
-- in their OWN `ba_` namespace so they never collide with the DOMAIN `users` table (0001).
-- Generated by `@better-auth/cli generate` against apps/web/lib/auth-server.ts (better-auth
-- 1.6.13, modelName = ba_user / ba_session / ba_account / ba_verification), wrapped with
-- IF NOT EXISTS for idempotency.

CREATE TABLE IF NOT EXISTS "ba_user" (
  "id"            text NOT NULL PRIMARY KEY,
  "name"          text NOT NULL,
  "email"         text NOT NULL UNIQUE,
  "emailVerified" boolean NOT NULL,
  "image"         text,
  "createdAt"     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"     timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "ba_session" (
  "id"        text NOT NULL PRIMARY KEY,
  "expiresAt" timestamptz NOT NULL,
  "token"     text NOT NULL UNIQUE,
  "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamptz NOT NULL,
  "ipAddress" text,
  "userAgent" text,
  "userId"    text NOT NULL REFERENCES "ba_user" ("id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ba_account" (
  "id"                    text NOT NULL PRIMARY KEY,
  "accountId"             text NOT NULL,
  "providerId"            text NOT NULL,
  "userId"                text NOT NULL REFERENCES "ba_user" ("id") ON DELETE CASCADE,
  "accessToken"           text,
  "refreshToken"          text,
  "idToken"               text,
  "accessTokenExpiresAt"  timestamptz,
  "refreshTokenExpiresAt" timestamptz,
  "scope"                 text,
  "password"              text,
  "createdAt"             timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"             timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS "ba_verification" (
  "id"         text NOT NULL PRIMARY KEY,
  "identifier" text NOT NULL,
  "value"      text NOT NULL,
  "expiresAt"  timestamptz NOT NULL,
  "createdAt"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "ba_session_userId_idx"          ON "ba_session" ("userId");
CREATE INDEX IF NOT EXISTS "ba_account_userId_idx"          ON "ba_account" ("userId");
CREATE INDEX IF NOT EXISTS "ba_verification_identifier_idx" ON "ba_verification" ("identifier");
